#!/bin/bash

# Setup automatic DHCP
cd  /etc/systemd/network/
touch prgmrDhcp.network
echo "[Match]"  >> prgmrDhcp.network
echo "Name=e*"  >> prgmrDhcp.network
echo >> prgmrDhcp.network
echo "[Network]"  >> prgmrDhcp.network
echo "DHCP=v4"  >> prgmrDhcp.network
systemctl enable systemd-networkd.service
systemctl enable systemd-resolved

# Disable ipv6 autoconfig
touch /etc/sysctl.d/40-ipv6.conf
echo "net.ipv6.conf.all.autoconf=0" >> /etc/sysctl.d/40-ipv6.conf
echo "net.ipv6.conf.all.use_tempaddr=0" >> /etc/sysctl.d/40-ipv6.conf
echo "net.ipv6.conf.eth0.accept_ra = 0" >> /etc/sysctl.d/40-ipv6.conf

# ssh configuration
sed -i -e 's/#PermitRootLogin yes/PermitRootLogin without-password/g' \
-e 's/PasswordAuthentication yes/PasswordAuthentication no/g' \
/etc/ssh/sshd_config

## ^ Consider also disabling insecure Protocol 1, as follows...
#-e 's/^#Protocol 2/Protocol 2/g' \
## source: http://www.nixtutor.com/linux/installing-and-configuring-an-ssh-server/

# install grub
PATH=/usr/local/sbin:$PATH
grub-install --target=i386-pc --recheck /dev/xvda

# configure grub
grub-mkconfig -o /boot/grub/grub.cfg

# clear ssh & pacman keys
rm /etc/ssh/ssh*key* 2>/dev/null
rm -r /etc/pacman.d/gnupg 2>/dev/null

# Some misc package configs
pacman -R logrotate
systemctl enable ntpd

# Default locale and things
sed -i -e 's/#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/g' /etc/locale.gen
locale-gen
echo 'LANG=en_US.UTF-8' > /etc/locale.conf
echo 'KEYMAP=us' > /etc/vconsole.conf

# this command causes an error to be raised about the command not being found
# prgmr-on-init-launch.s* /mnt/opt/install

cp /opt/install/prgmr-on-init-launch.service /etc/systemd/system/prgmr-on-init-launch.service
cp /opt/install/prgmr-on-init-launch.sh /usr/local/sbin/prgmr-on-init-launch.sh

systemctl enable prgmr-on-init-launch
