#!/bin/bash
# Select the mirrors

echo "Server = http://mirrors.kernel.org/archlinux/\$repo/os/\$arch" > /etc/pacman.d/mirrorlist

# Get the security keys sorted out
# Produce 'entropy' for key gen, these keys are deleted after install
# haveged can be used after this, which is faster
(while true; do dd if=/dev/xvda of=/dev/null; done ) &
export ENTROPY_GEN=$!
pacman-key --init
kill -- -${ENTROPY_GEN}
pacman-key --populate archlinux

# install the system and change into new root
e2label /dev/xvda1 PRGMRDISK1
e2label /dev/xvda3 PRGMRDISK3

mount /dev/xvda1 /mnt
mkdir /mnt/var
mount /dev/xvda3 /mnt/var
swapon /dev/xvda2

pacstrap /mnt base base-devel vim net-tools screen linux-lts grub haveged openssh cronie syslog-ng ntp exim letsencrypt openvpn
genfstab -p /mnt >> /mnt/etc/fstab
cp /etc/resolv.conf /mnt/etc
umount -R /mnt
exit
