#!/bin/bash
# Select the mirrors

echo "Server = http://mirrors.kernel.org/archlinux/\$repo/os/\$arch" >> /etc/pacman.d/mirrorlist
echo "Server = http://mirrors.xmission.com/archlinux/$repo/os/$arch" >> /etc/pacman.d/mirrorlist

# Get the security keys sorted out
# Produce 'entropy' for key gen, these keys are deleted after install
# haveged can be used after this, which is faster
(while true; do dd if=/dev/xvda of=/dev/null; done ) &
export ENTROPY_GEN=$!
pacman-key --init
kill -- -${ENTROPY_GEN}
pacman-key --populate archlinux

# install the system and change into new root
mount /dev/xvda1 /mnt
mkdir /mnt/var /mnt/srv
mount /dev/xvda3 /mnt/var
mount /dev/xvda4 /mnt/srv
pacstrap /mnt base base-devel vim net-tools screen linux-lts grub haveged openssh cronie syslog-ng ntp exim certbot openvpn

genfstab -p /mnt >> /mnt/etc/fstab
cp /etc/resolv.conf /mnt/etc
umount -R /mnt
exit
